In [1]:
import pooled_ppi as pp

In [2]:
pp.string_db.read(data_id='protein.links', cols_rm_organism={'protein1', 'protein2'}).head(3)

  protein1 protein2  combined_score
0    Q0010  YMR207C             333
1    Q0010  YCR051W             205
2    Q0010  YPR002W             195

In [3]:
pp.string_db.read(data_id='protein.links.detailed', cols_rm_organism={'protein1', 'protein2'}).head(3)

,protein1,protein2,neighborhood,fusion,cooccurence,coexpression,experimental,database,textmining,combined_score
0,Q0010,YMR207C,45,0,0,95,0,245,99,333
1,Q0010,YCR051W,0,0,0,0,180,0,71,205
2,Q0010,YPR002W,0,0,0,52,116,0,117,195

In [4]:
pp.string_db.read(data_id='protein.physical.links.full', cols_rm_organism={'protein1', 'protein2'}).head(3)

,protein1,protein2,homology,experiments,experiments_transferred,database,database_transferred,textmining,textmining_transferred,combined_score
0,Q0045,YGR222W,0,292,0,0,0,0,0,292
1,Q0045,Q0120,0,0,170,0,0,0,166,278
2,Q0045,YML030W,0,734,0,0,0,0,0,734

In [5]:
pp.string_db.read(data_id='protein.info', cols_rm_organism={'string_protein_id'}).head(3)

,string_protein_id,preferred_name,protein_size,annotation
0,Q0010,Q0010,128,"Putative uncharacterized protein Q0010, mitoch..."
1,Q0017,Q0017,53,"Putative uncharacterized protein Q0017, mitoch..."
2,Q0032,Q0032,96,"Putative uncharacterized protein Q0032, mitoch..."

In [6]:
pp.string_db.read(data_id='protein.aliases', cols_rm_organism={'string_protein_id'})['source'].value_counts()

source
Ensembl_protein_id                     21053
UniProt_DR_PDB                         20231
Ensembl_PDB                            17074
UniProt_AC                             14066
Ensembl_RefSeq                         11856
Ensembl_RefSeq_short                   11856
UniProt_DR_RefSeq                      11624
SGD_ID                                 10510
KEGG_PRODUCT                            8531
SGD_SYNONYM                             6792
Ensembl_UniProt                         6781
Ensembl_transcript                      6600
Ensembl_translation                     6600
Ensembl_gene                            6600
Ensembl                                 6600
SGD_PRIMARY                             6600
Ensembl_UniParc                         6596
UniProt_GN_OrderedLocusNames            6522
UniProt_DR_SGD                          6522
UniProt_ID                              6517
Ensembl_STRING                          6030
UniProt_DE_RecName_Full                 5975
Ensembl_EntrezGene                      5925
KEGG_NCBI                               5854
KEGG_KEGGID                             5854
KEGG_GENEID                             5854
KEGG_KEGGID_SHORT                       5854
UniProt_DR_GeneID                       5812
KEGG_NAME                               5171
SGD_NAME                                5140
UniProt_DE_AltName_Full                 5110
UniProt_GN_Name                         5059
UniProt_GN_ORFNames                     3996
KEGG_EC                                 3300
KEGG_NAME_SYNONYM                       2961
Ensembl_external_synonym_EntrezGene     2724
UniProt_GN_Synonyms                     2532
UniProt_DE_RecName_EC                   1770
Ensembl_EMBL                            1137
UniProt_DE_RecName_Short                 810
UniProt_DE_AltName_Short                 570
Ensembl_description                      133
Ensembl_MEROPS                           127
Ensembl_ChEMBL                            77
UniProt_DE_AltName_EC                     69
Ensembl_PHI                                2
SGD_NAME_Paralog                           1
Name: count, dtype: int64